version: 2

sources:
#date
  - name: conformed
    database: raw
    schema: conformed

    tables:
      - name: DateDimension
        columns:
          - name: DateKey
            tests:
              - unique
  # Fudgemart raw tables
  - name: fudgemart_v3
    database: RAW
    schema: fudgemart_v3
    tables:
      - name: fm_orders
      - name: fm_order_details
      - name: fm_customers
      - name: fm_products
      - name: fm_shipvia_lookup
      - name: fm_vendors
      - name: fm_creditcards
      - name: fm_customer_creditcards

  # Fudgeflix raw tables
  - name: fudgeflix_v3
    database: RAW
    schema: fudgeflix_v3
    tables:
      - name: ff_account_titles
      - name: ff_accounts
      - name: ff_titles
      - name: ff_plans
      - name: ff_zipcodes
      - name: ff_account_billing
      - name: ff_title_genres